### ISSUE TITLE
error using code

### ISSUE THREAD

**Issue by haibianshifeng** [jdechalendar/pnm-generation#1]
When run the code， the error about kdeJAC appears.
The content of error is ''Error using kde.kde ,Too many output arguments.''.

When run the code, the error about generateCylThroats appears.
The content of error is ''Undefined function 'istril' for input arguments of type 'double'.''.

**Comment by jdechalendar** [comment]
What version of MATLAB are you using? The code was developped using 2014a, but I just checked on another computer running 2016a, and I was able to go through the generatePNM test file without any issue. You can change the number of target bodies in there (I just used 500) if you want to make it run faster for testing

For both errors , could you send me a small snippet of code you are running that generates the error?

For the second one, the istril function checks whether a matrix is lower triangular. For some reason you are not passing in a matrix but a float.

**Comment by haibianshifeng** [comment]
My MATLAB version is R2013a and the operating system is Windows 7 64 bit.

I downloaded the code form the github (
https://github.com/jdechalendar/pnm-generation).

I run the setup.m and generatePNM.m in sequence.

the error is as the picture




2017-04-10 23:40 GMT+08:00 Jacques de Chalendar <notifications@github.com>:

**Comment by jdechalendar** [comment]
I would be surprised if this were a version issue. Which picture are you referring to? Did you upload one? If yes, I do not see it.

One thing you can try to do is to run the code in generatePNM cell by cell, to get an idea of where the bug is occurring. It will be difficult for me to help if I cannot reproduce the error.

**Comment by haibianshifeng** [comment]
I had upload the picture. Which version is right? How to change the code to
run it by MATLAB R2013a?

2017-04-11 9:38 GMT+08:00 Jacques de Chalendar <notifications@github.com>:

**Comment by haibianshifeng** [comment]
I can send it to your E-mail?

2017-04-11 9:44 GMT+08:00 刘磊 <liuleigbd@gmail.com>:

**Comment by jdechalendar** [comment]
Are you attaching the picture in an email? If yes, I think this may be why it is not uploaded properly. I think you need to go here https://github.com/jdechalendar/pnm-generation/issues/1 if you want to upload a picture. The easiest may just be to copy/paste the text output though.

**Comment by haibianshifeng** [comment]
The content of error about kdeJAC.m are as follow:

*Error using nanmean*
*Too many input arguments.*

*Error in skewness (line 39)*
*x0 = x - repmat(nanmean(x,dim), tile);*

*Error in kdeJAC (line 103)*
*                fprintf(opt.fID_log, 'Skewness\t%4g\n', skewness(vec));*

*Error in generatePNM (line 34)*
*kdeJAC(vec)*

2017-04-11 9:49 GMT+08:00 Jacques de Chalendar <notifications@github.com>:

**Comment by jdechalendar** [comment]
For now, can you simply comment out line 103 in kdeJAC and tell me what happens?
Both skewness and nanmean are built-in MATLAB functions, so this may actually be a version issue after all.
If that works, maybe try checking what is being passed into skewness (the vec object). This part of the code is outputting statistics on the results. Is the plot with the bodies in the first cell being generated correctly?

**Comment by haibianshifeng** [comment]
Yes. You are right. I change the MATLAB to the version of R2015b. The error
disappears. However, the new error appears.

The content of new error are as follow:

error use generateCylThroats (line 46)
there does not seem to be enough "space" -> try again

error generatePNM (line 62)
[bodies,throats,coord,adj] = generateCylThroats(bodies,dist,target, verb);

2017-04-11 9:57 GMT+08:00 Jacques de Chalendar <notifications@github.com>:

**Comment by jdechalendar** [comment]
That error is more expected. The algorithm tries to generate a pore space based on the given distributions for parameters, but depending on where you start, the algorithm does not always succeed.

If this message appears, rerun the corresponding cell (the one to generate the throats). If this error occurs several times in a row, I would restart from the beginning to get another set of bodies. On my computer, I sometimes get this error, but usually after a try or two I can generate a network.

**Comment by haibianshifeng** [comment]
OK Your are right， many thanks.

2017-04-11 14:55 GMT+08:00 Jacques de Chalendar <notifications@github.com>:

**Comment by haibianshifeng** [comment]
I had solved the error for using MATLAB R2013a.

Three functions are needed, which is istril.m (
https://cn.mathworks.com/matlabcentral/fileexchange/31125-trilin?focused=5186248&tab=function),
issquare.m (
https://cn.mathworks.com/matlabcentral/fileexchange/31125-trilin?focused=5186246&tab=function)
and issymmetric.m.

You can add them to the project.


2017-04-11 15:36 GMT+08:00 刘磊 <liuleigbd@gmail.com>:
